channels:
  - conda-forge
  - defaults
  - damianavila82
dependencies:
  - python
  - numpy
  - matplotlib
  - xarray
  - metpy
  - sympy
  - ffmpeg
  - jupyter
  - climlab
  - version_information
  - rise
