name: climlab-courseware
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - matplotlib
  - xarray
  - metpy
  - cartopy
  - sympy
  - ffmpeg
  - jupyter
  - climlab>=0.7.5
  - version_information
  - rise
  - numba>=0.43.1
  - netcdf4
